FEConf 2021 추가합니다.
brave-people/Dev-Event pull request #84
Opened 2021-07-12 08:31 UTC by saseungmin

- FEConf 2021 일정이 나와서 추가합니다.

현재 [FEConf 홈페이지](https://feconf.kr/)는 FEConf 2020으로 2021로 업데이트가 안되어있어서 [Facebook에 올라온 게시글](https://www.facebook.com/groups/webfrontend/permalink/2383618995116155/)의 FEConf 2021 링크를 [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSe28Zun8Dne5t78sIwIEhp8bpYv0nsSbvTlngXez3HdCucZFg/viewform)으로 해놓았습니다.

**추후 홈페이지가 업데이트되면 변경하겠습니다.**

- Contributor의 제 블로그로 링크가 되어있는것을 제 Github 링크로 변경하였습니다.
- 기타(정규적으로 열리는 개발자 행사입니다.)에 FEConf를 추가했습니다.

2021-07-12 09:05 UTC, KoEonYack commented
@saseungmin 님! 감사합니다!

FEConf 일정을 기다렸는데 나왔군요~!

그런데 수정하신 커밋 중에서 링크를 변경해주셨는데요!

```
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
```

주석 영역은 allcontributor가 관리하는 영역이고 .all-contributorsrc와 싱크가 맞추어서 돌아갑니다. 

그래서 수정할 경우 bot이 동작하지 않습니다!

해당 부분을 원복해주시면 merge하도록 하겠습니다!!

관심을 갖고 다시 PR 올려주심에 다시한번 감사드립니다! 🙏

2021-07-12 09:05 UTC, KoEonYack requested changes
@saseungmin 님! 감사합니다!

FEConf 일정을 기다렸는데 나왔군요~!

그런데 수정하신 커밋 중에서 링크를 변경해주셨는데요!

```
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
```

주석 영역은 allcontributor가 관리하는 영역이고 .all-contributorsrc와 싱크가 맞추어서 돌아갑니다. 

그래서 수정할 경우 bot이 동작하지 않습니다!

해당 부분을 원복해주시면 merge하도록 하겠습니다!!

관심을 갖고 다시 PR 올려주심에 다시한번 감사드립니다! 🙏

2021-07-12 11:48 UTC, saseungmin commented
앗! 그렇군요. 변경하겠습니다. 😅
감사합니다! 🙏

2021-07-12 12:52 UTC, KoEonYack approved these changes
감사합니다!! :)

2021-07-12 12:52 UTC, merged

2021-07-26 07:40 UTC, Saseungwon commented
good